import type { ReportRenderer } from '../renderer.js'
import type { SecurityReport, SecurityFinding, TaintFlow } from '../types.js'

export class MarkdownReporter implements ReportRenderer<string> {
  public readonly name = 'MarkdownReporter'
  public readonly format = 'markdown'
  public readonly contentType = 'text/markdown; charset=utf-8'

  public render(report: SecurityReport): string {
    const { metadata, summary, findings, methodology } = report
    const dist = summary.distribution

    let md = `# VulScan Security Assessment Report: ${metadata.target.repositoryName}\n\n`

    // Metadata callout block
    md += `> **Repository:** \`${metadata.target.repositoryUrl}\`  \n`
    md += `> **Branch:** \`${metadata.target.branch}\`  \n`
    md += `> **Scan Timestamp:** ${new Date(metadata.scan.timestamp).toUTCString()}  \n`
    md += `> **Scan Duration:** ${metadata.scan.durationMs}ms  \n`
    md += `> **Files Analyzed:** ${metadata.scan.filesAnalyzed}  \n\n`
    md += `---\n\n`

    // Security Posture Section
    md += `## 1. Security Posture\n\n`
    if (dist.critical > 0) {
      md += `> [!CAUTION]\n`
      md += `> **${dist.critical} CRITICAL-SEVERITY VULNERABILIT${dist.critical === 1 ? 'Y' : 'IES'} FLAGGED**\n`
      md += `> Immediate remediation required. Exploit paths reach dangerous execution sinks without security boundaries.\n\n`
    } else if (dist.high > 0) {
      md += `> [!CAUTION]\n`
      md += `> **${dist.high} HIGH-SEVERITY VULNERABILIT${dist.high === 1 ? 'Y' : 'IES'} DETECTED**\n`
      md += `> Action required prior to deployment. Unsanitized user inputs flow into critical execution sinks.\n\n`
    } else if (dist.medium > 0) {
      md += `> [!WARNING]\n`
      md += `> **${dist.medium} MEDIUM-SEVERITY FINDING${dist.medium === 1 ? '' : 'S'} IDENTIFIED**\n`
      md += `> Review recommended. Certain application inputs require defense-in-depth sanitization.\n\n`
    } else {
      md += `> [!NOTE]\n`
      md += `> **CLEAN POSTURE: ZERO VULNERABILITIES DETECTED**\n`
      md += `> All evaluated execution sinks and data flows adhere to secure coding patterns.\n\n`
    }

    // Severity Distribution Table
    md += `### Severity Distribution\n\n`
    md += `| Severity | Findings Count | Priority |\n`
    md += `|:---|---:|:---|\n`
    md += `| **CRITICAL** | ${dist.critical} | P0 — Immediate Block |\n`
    md += `| **HIGH** | ${dist.high} | P1 — Release Blocker |\n`
    md += `| **MEDIUM** | ${dist.medium} | P2 — Hardening Required |\n`
    md += `| **LOW** | ${dist.low} | P3 — Hygiene / Best Practice |\n`
    md += `| **INFO** | ${dist.info} | P4 — Informational |\n\n`

    md += `**Overall Verdict:** \`${summary.statusVerdict}\`\n\n`
    md += `---\n\n`

    // Executive Summary
    md += `## 2. Executive Summary\n\n`
    md += `${summary.executiveBrief}\n\n`
    md += `The static analysis evaluated **${metadata.scan.filesAnalyzed}** files across branch \`${metadata.target.branch}\` utilizing **${methodology.rules.length}** security rules. `
    if (findings.length === 0) {
      md += `No injection patterns or unparameterized sinks were found.\n\n`
    } else {
      md += `A total of **${findings.length}** finding(s) were flagged for developer remediation.\n\n`
    }

    md += `---\n\n`

    // Findings Overview Table
    md += `## 3. Findings Overview\n\n`
    md += `| ID | Finding Name | Severity | CWE | Location | Status |\n`
    md += `|:---|:---|:---:|:---:|:---|:---:|\n`

    if (findings.length === 0) {
      md += `| — | *Clean Scan (No findings)* | Clean | — | — | PASSED |\n`
    } else {
      findings.forEach((f) => {
        md += `| [${f.id}](#${f.id.toLowerCase()}) | ${f.rule.name} | **${f.severity}** | \`${f.rule.cwe}\` | \`${f.location.file}:${f.location.line}\` | \`${f.status.toUpperCase()}\` |\n`
      })
    }

    md += `\n---\n\n`

    // Detailed Findings Section
    md += `## 4. Detailed Vulnerability Analyses\n\n`

    if (findings.length === 0) {
      md += `*No vulnerabilities flagged for repository \`${metadata.target.repositoryName}\`.*\n\n`
    } else {
      findings.forEach((f, idx) => {
        md += this.renderFindingMarkdown(f, idx + 1)
      })
    }

    // Methodology Section
    md += `## 5. Assessment Methodology\n\n`
    md += `${methodology.description}\n\n`
    md += `### Rules Executed\n\n`
    methodology.rules.forEach(r => {
      md += `#### \`${r.id}\` — ${r.name} (\`${r.cwe}\`)\n`
      md += `- **Category:** ${r.category}\n`
      md += `- **Detection Strategy:** ${r.detectionStrategy}\n`
      md += `- **Target Sinks:** ${r.sinks.map(s => `\`${s}\``).join(', ')}\n\n`
    })

    // Footer
    md += `---\n\n`
    md += `*Generated by ${metadata.scanner.name}.*\n`

    return md
  }

  private renderFindingMarkdown(finding: SecurityFinding, _orderNum: number): string {
    let fMd = `### [${finding.severity}] ${finding.id} — ${finding.rule.name}\n\n`

    fMd += `**Severity:** \`${finding.severity}\` | `
    fMd += `**CWE:** [\`${finding.rule.cwe}\`](https://cwe.mitre.org/data/definitions/${finding.rule.cwe.replace('CWE-', '')}.html) | `
    fMd += `**Rule:** \`${finding.rule.id}\` | `
    fMd += `**Confidence:** \`${finding.confidence}%\` | `
    fMd += `**Status:** \`${finding.status.toUpperCase()}\`\n\n`

    fMd += `> ${finding.rawMessage}\n\n`

    // Location & Taint Sink
    fMd += `#### Finding Location & Flagged Sink\n`
    fMd += `- **File:** \`${finding.location.file}:${finding.location.line}:${finding.location.column || 1}\`\n`
    fMd += `- **Execution Sink:** \`${finding.taintFlow.sink.expression}\`\n`
    fMd += `- **Untrusted Source:** \`${finding.taintFlow.source.expression}\`\n\n`

    // Taint Flow ASCII Diagram
    fMd += `#### Taint Propagation Flow\n`
    fMd += `\`\`\`text\n`
    fMd += this.renderTaintFlowAscii(finding.taintFlow)
    fMd += `\`\`\`\n\n`

    // Code Evidence
    fMd += `#### Flagged Code Evidence\n`
    fMd += `\`\`\`${finding.evidence.language}\n`
    fMd += this.formatCodeWithLineNumbers(finding.evidence.code, finding.evidence.startLine, finding.location.line)
    fMd += `\`\`\`\n\n`

    // Security Advisory & Taint Analysis
    if (finding.analysis) {
      fMd += `#### Security Advisory & Taint Analysis\n`
      fMd += `- **Triage Evaluator:** \`${finding.analysis.model}\`\n`
      fMd += `- **Verdict:** ${finding.analysis.verdict === 'CONFIRMED' ? '**CONFIRMED VULNERABILITY**' : finding.analysis.verdict === 'FALSE_POSITIVE' ? '**FALSE POSITIVE**' : '**NEEDS MANUAL REVIEW**'} (\`${finding.analysis.confidence}%\` confidence)\n`
      if (finding.analysis.sanitizerDetected) {
        fMd += `- **Sanitizer Detection:** *Active sanitizer or encoder evaluated in scope*\n`
      }
      if (finding.analysis.safeCastDetected) {
        fMd += `- **Typecast Detection:** *Safe primitive conversion evaluated in scope*\n`
      }
      fMd += `\n**Audit Reasoning:**\n\n`
      fMd += `${finding.analysis.reasoning}\n\n`
    }

    // Impact Section
    fMd += `#### Security Impact & Consequences\n`
    fMd += `${finding.impact.description}\n\n`
    fMd += `**Potential Consequences:**\n`
    finding.impact.consequences.forEach(c => {
      fMd += `- ${c}\n`
    })
    if (finding.impact.cvssVector) {
      fMd += `\n**Severity Rating:** \`${finding.impact.cvssVector}\`\n`
    }
    fMd += `\n`

    // Remediation Section
    fMd += `#### Recommended Remediation\n`
    fMd += `${finding.remediation.explanation}\n\n`
    if (finding.remediation.code) {
      fMd += `**Preferred Hardened Implementation:**\n\n`
      fMd += `\`\`\`${finding.remediation.language || 'javascript'}\n`
      fMd += `${finding.remediation.code}\n`
      fMd += `\`\`\`\n\n`
    }
    if (finding.remediation.documentationUrl) {
      fMd += `*Reference:* [OWASP Remediation Guidance](${finding.remediation.documentationUrl})\n\n`
    }

    fMd += `---\n\n`
    return fMd
  }

  private renderTaintFlowAscii(flow: TaintFlow): string {
    const lines: string[] = []
    lines.push(`SOURCE: ${flow.source.expression}`)
    lines.push(`        │`)
    lines.push(`        ▼`)

    if (flow.transformations && flow.transformations.length > 0) {
      flow.transformations.forEach(t => {
        lines.push(`TRANSFORMATION: ${t.label} [${t.expression}]`)
        lines.push(`        │`)
        lines.push(`        ▼`)
      })
    }

    lines.push(`SINK:   ${flow.sink.expression} (${flow.sink.label})`)
    return lines.join('\n')
  }

  private formatCodeWithLineNumbers(code: string, startLine: number, highlightLine: number): string {
    const lines = code.split('\n')
    return lines
      .map((line, idx) => {
        const currentLine = startLine + idx
        const isFlagged = currentLine === highlightLine
        const prefix = isFlagged ? '>>> ' : '    '
        const lineNumStr = String(currentLine).padStart(4, ' ')
        return `${prefix}${lineNumStr} │ ${line}`
      })
      .join('\n')
  }
}
